id: I73180C35
legacy_id: P000734
ocr_import_info:
  bdrc_scan_id: W14322
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T07:12:51'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T13:08:44.913996+00:00'
last_modified: 2022-08-30 21:12:26.799471
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W14322
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW14322
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཐོབ་ཡིག་༔་བློ་བཟང་འཕྲིན་ལས།
  author: ཛ་ཡ་པཎྜི་ཏ་བློ་བཟང་འཕྲིན་ལས།
statistics:
  ocr_word_mean_confidence_index: 0.6278580123656602
  ocr_word_median_confidence_index: 0.7099999785423279
quality: null
bases:
  I5603:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5603
      total_pages: 640
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I5603.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6194871168020121
    legacy_id: v003
  I5601:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5601
      total_pages: 598
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5601.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.6376557496842238
    legacy_id: v001
  I5602:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5602
      total_pages: 636
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I5602.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6079697009564998
    legacy_id: v002
  I5604:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5604
      total_pages: 608
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I5604.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6533500342563286
    legacy_id: v004
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
