id: I73180C35
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T07:17:51+00:00'
last_modified: '2022-06-07T13:35:40.055595+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W14322
  title: ཐོབ་ཡིག་༔་བློ་བཟང་འཕྲིན་ལས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    9A7A:
      image_group_id: I5601
      title: ''
      total_pages: 598
      order: 1
      base_file: 9A7A.txt
    907B:
      image_group_id: I5602
      title: ''
      total_pages: 636
      order: 2
      base_file: 907B.txt
    14F4:
      image_group_id: I5603
      title: ''
      total_pages: 640
      order: 3
      base_file: 14F4.txt
    E09B:
      image_group_id: I5604
      title: ''
      total_pages: 608
      order: 4
      base_file: E09B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
