id: P000734
initial_creation_type: ocr
source_metadata:
  id: bdr:W14322
  title: ཐོབ་ཡིག་༔་བློ་བཟང་འཕྲིན་ལས
  author: ''
  volumes:
    2a267dcf4c324154a51eb38db83494ec:
      image_group_id: I5601
      title: ''
      volume_number: 1
      total_pages: 598
    1666222befa942ba9824997a7aefa6e7:
      image_group_id: I5602
      title: ''
      volume_number: 2
      total_pages: 636
    f6bbb86fc38b4f30bf9c498d0bfcb670:
      image_group_id: I5603
      title: ''
      volume_number: 3
      total_pages: 640
    76d592e4050b4513be7fd19c8cd96a9d:
      image_group_id: I5604
      title: ''
      volume_number: 4
      total_pages: 608
